#!/usr/bin/env python

# ------------------------------
# License

# Copyright 2023 Aldrin Montana
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ------------------------------
# Overview
"""
Simple script that uses mohair_extension to translate a query plan into substrait.
"""


# ------------------------------
# Dependencies

# >> Standard modules
from pathlib import Path

# >> Third-party
from ibis_substrait.compiler.core import SubstraitCompiler
from ibis_substrait.proto.substrait.ibis.plan_pb2 import Plan


# ------------------------------
# Module variables

example_input = Path('resources') / 'average-expression.substrait'


if __name__ == '__main__':
    # initialize a protobuf structure
    substrait_plan = Plan()

    # populate the protobuf structure from binary
    with open(example_input, 'rb') as file_handle:
        substrait_plan.ParseFromString(file_handle.read())

    # print the structure
    print(substrait_plan)
