# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mohair/algebra.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14mohair/algebra.proto\x12\x06mohair\x1a\x19google/protobuf/any.proto\"F\n\x0e\x45xecutionStats\x12\x1a\n\x08\x65xecuted\x18\x01 \x01(\x08R\x08\x65xecuted\x12\x18\n\x07runtime\x18\x02 \x01(\x01R\x07runtime\"\x8c\x01\n\x06SkyRel\x12\x16\n\x06\x64omain\x18\x01 \x01(\tR\x06\x64omain\x12\x1c\n\tpartition\x18\x02 \x01(\tR\tpartition\x12\x16\n\x06slices\x18\x03 \x03(\rR\x06slices\x12\x34\n\texecstats\x18\x04 \x01(\x0b\x32\x16.mohair.ExecutionStatsR\texecstats\"\x90\x01\n\nKineticRel\x12\x16\n\x06\x64omain\x18\x01 \x01(\tR\x06\x64omain\x12\x1c\n\tpartition\x18\x02 \x01(\tR\tpartition\x12\x16\n\x06slices\x18\x03 \x03(\rR\x06slices\x12\x34\n\texecstats\x18\x04 \x01(\x0b\x32\x16.mohair.ExecutionStatsR\texecstats\" \n\x08QueryRel\x12\x14\n\x05query\x18\x01 \x01(\x0cR\x05queryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mohair.algebra_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXECUTIONSTATS._serialized_start=59
  _EXECUTIONSTATS._serialized_end=129
  _SKYREL._serialized_start=132
  _SKYREL._serialized_end=272
  _KINETICREL._serialized_start=275
  _KINETICREL._serialized_end=419
  _QUERYREL._serialized_start=421
  _QUERYREL._serialized_end=453
# @@protoc_insertion_point(module_scope)
